Cb save image link
AppFolioOnboarding/image-sharer-kimiamajd98 pull request #10
Opened 2021-07-07 17:31 UTC by kimiamajd98

Closes #2 

---

The following is a checklist to remind you of the steps to take when opening a
new PR. The horizontal line above and everything below can be removed from the
pull request description.

- [ ] I have replaced `X` above with the associated issue number.
- [ ] I have changed the issue's label to "pull request".
- [ ] I have assigned the designated reviewer to this PR.
- [ ] I have set the appropriate label on this PR.
- [ ] I have written clear commit messages ([ref](http://chris.beams.io/posts/git-commit/)).

If needed, please review the document on the
[Image Sharing Project](https://sites.google.com/a/appfolio.com/eng/new-hire-resources/engineering-academy/ropes/image-sharing-project)
for information on how labels should be used.

2021-07-07 21:15 UTC, sarahsehr commented
> The following is a checklist to remind you of the steps to take when opening a
new PR. The horizontal line above and everything below can be removed from the
pull request description.

It looks like some of these items still need to be completed.

2021-07-07 21:17 UTC, sarahsehr commented on app/controllers/application_controller.rb
> +  def form; end
Will it be problematic to continue to add new actions to this controller? What would be a good way to organize the various actions?

Is `form` a descriptive enough name? Will all forms in this application use this same action? If not, how will we tell this one from others?

2021-07-07 21:19 UTC, kimiamajd98 commented on app/controllers/application_controller.rb
> +  def form; end
Oops! I should have deleted form. I stopped using form once I turned image into an action and I put the rest of the methods into the image controller. Will remove form and commit right now!

2021-07-07 21:22 UTC, sarahsehr commented on app/views/application/form.html.erb
> +    <%= form.label :url %><br>
When should you use `br` vs `div`?

2021-07-07 21:22 UTC, sarahsehr commented on config/routes.rb
> +  resources :images
Do you need all the routes that this will generate?

2021-07-07 21:24 UTC, sarahsehr commented on app/controllers/images_controller.rb
> +  def create
This controller is committed without a test. Do you see any consequences to this?

2021-07-07 21:24 UTC, sarahsehr commented on app/controllers/images_controller.rb
> +
This little circle with a line through it has meaning, do you know what it is?

2021-07-07 21:25 UTC, sarahsehr commented on app/models/image.rb
> +  validates :url, presence: true, url : true
Test?

2021-07-07 21:26 UTC, sarahsehr commented on app/models/image.rb
> +  validates :url, presence: true, url : true
Is this valid Ruby?

2021-07-07 21:26 UTC, sarahsehr commented on app/controllers/images_controller.rb
> +    @image = Image.find(params[:id])
Test?

2021-07-07 21:27 UTC, sarahsehr commented on app/controllers/images_controller.rb
> +class ImagesController < ActionController::Base
Is this the parent class that the tutorials say to use?

2021-07-07 21:28 UTC, sarahsehr commented on app/views/application/home.html.erb
> +<%=link_to "Image Submission Form", new_image_path%>
Does this line follow Ruby styles?

2021-07-07 21:29 UTC, sarahsehr commented on config/routes.rb
> -  get '/form', to: 'application#form', as: 'form'
Do we still need the form action in ApplicationController?

2021-07-07 21:30 UTC, sarahsehr commented on app/views/images/show.html.erb
> +<h1><%= @image.url %><\h1>
What is the semantic meaning of an `h1`?

2021-07-07 21:30 UTC, kimiamajd98 commented on config/routes.rb
> -  get '/form', to: 'application#form', as: 'form'
No, it's not in the latest commit!

2021-07-07 21:30 UTC, sarahsehr commented on app/models/image.rb
> +  validates :url, presence: true, format: {
How can we verify that this works the way we expect?

2021-07-07 21:32 UTC, sarahsehr commented on app/controllers/application_controller.rb
> +
Are there any consequences to these style changes being in their own commit?

2021-07-07 21:32 UTC, kimiamajd98 commented on app/views/images/show.html.erb
> +<h1><%= @image.url %><\h1>
It's a primary header. That line was just for my own testing purposes. I was having trouble getting the image to show and wanted to see if I could even get the url to show and I accidentally committed it. That line isn't in the latest commit!

2021-07-07 21:33 UTC, sarahsehr requested changes
I've added a few questions to think about. Most are trying to hint at a change that should be made.

One other question. What is the role of the `ApplicationController` class? Why does it exist and how and when would it be used?

2021-07-07 21:37 UTC, kimiamajd98 commented on app/views/application/form.html.erb
> +    <%= form.label :url %><br>
br should be used as a line break while div is used to signify a block level element. This should probably be wrapped in a div rather than a br.

2021-07-07 21:47 UTC, kimiamajd98 commented on config/routes.rb
> +  resources :images
No I only need index, show, new, destroy, and create

2021-07-08 18:29 UTC, kimiamajd98 commented on app/controllers/images_controller.rb
> +  def create
added tests!

2021-07-08 18:31 UTC, kimiamajd98 commented on app/controllers/images_controller.rb
> +
newline needed at end of file, fixed!

2021-07-08 18:31 UTC, kimiamajd98 commented on app/models/image.rb
> +  validates :url, presence: true, url : true
Added image model tests and this validation was wrong, I updated it in a following commit

2021-07-08 18:32 UTC, kimiamajd98 commented on app/controllers/images_controller.rb
> +    @image = Image.find(params[:id])
added tests

2021-07-08 18:36 UTC, kimiamajd98 commented on app/models/image.rb
> +  validates :url, presence: true, format: {
I added tests for the image model that verify that only valid / nonblank url's will be allowed

2021-07-08 18:37 UTC, kimiamajd98 commented on app/controllers/images_controller.rb
> +class ImagesController < ActionController::Base
No, the parent class should be application controller. Fixed!

2021-07-08 18:38 UTC, kimiamajd98 commented on app/controllers/application_controller.rb
> +
The style issues caused some of the circleCI tests to fail. I should have run rubocop before committing so the style changes weren't in a separate commit.

2021-07-08 18:41 UTC, kimiamajd98 commented on app/views/application/home.html.erb
> +<%=link_to "Image Submission Form", new_image_path%>
This one I'm not sure of.. I thought new_image_path was correct. Should it be new_image_url instead?

2021-07-08 21:55 UTC, sarahsehr commented on app/controllers/application_controller.rb
> +
Besides having to do all the work at the end, this can also affect future dev productivity. If someone is using Annotate (git "blame") to see what the history of a particular line, what they will see in style changes and not the actual changes in behavior that they are looking for. By running rubocop before committing each commit OR fixing up the styles changes into the correct commit, we can avoid this second problem.

2021-07-08 21:57 UTC, sarahsehr commented on app/controllers/images_controller.rb
> +      render :new, status: :unprocessable_entity
Good

2021-07-08 21:58 UTC, sarahsehr commented on app/views/images/new.html.erb
> +<h1 id = 'header'>Image Form</h1>
Does this work correctly with the spaces? I'm used to seeing this like `<h1 id='header'>Image Form</h1>`

2021-07-08 21:58 UTC, sarahsehr commented on test/controllers/images_controller_test.rb
> +    assert_select '#header', 'Image Form'
Is there anything else we can assert?

2021-07-08 22:00 UTC, sarahsehr commented on test/controllers/images_controller_test.rb
> +    assert_difference('Image.count', 1) do
Ruby style most commonly drops the parenthesis. `assert_difference 'Image.count', 1 do`

2021-07-08 22:00 UTC, sarahsehr commented on test/controllers/images_controller_test.rb
> +    end
Line 23 asserts that a new Image is created. Is there anything else that might be helpful to check about that creation?

2021-07-08 22:02 UTC, kimiamajd98 commented on app/views/images/new.html.erb
> +<h1 id = 'header'>Image Form</h1>
I think it did work correctly because the test passed but I will remove the spaces if that is the more common practice!

2021-07-08 22:16 UTC, kimiamajd98 commented on test/controllers/images_controller_test.rb
> +    end
I added an assertion to check if the url of the image just created matches the intended url. Not sure if there is anything else I should assert?

2021-07-09 00:07 UTC, sarahsehr commented on test/models/image_test.rb
> +  def test_image__valid
Test coverage on the unit level, like this model test, should be very thorough. That is, I shouldn't be able to delete any code in the model without a test failing. Do you have sufficient test coverage that I could do that?

2021-07-09 00:11 UTC, sarahsehr commented on test/controllers/images_controller_test.rb
> +    assert_select 'form input[name=?]', 'image[url]'
You don't need to change this, but for future reference. `assert_select` supports nested assertions:

```
assert_select 'form' do |form|
  assert_select form, 'input[name=?]', 'image[url]'
  assert_select form, 'input[value=?]', 'iCreate Image'
end
```

I find this example reads a little bit more clearly, but what you have is not wrong.

2021-07-09 00:12 UTC, sarahsehr commented on app/views/application/home.html.erb
> +<%=link_to "Image Submission Form", new_image_path%>
`<%= link_to "Image Submission Form", new_image_path %>`

I was referring to the spacing.

2021-07-09 00:18 UTC, sarahsehr commented on test/controllers/images_controller_test.rb
> +    assert_select 'img.img[src=?]', @image.url
One thing that I prefer is to use string literals as much as reasonably possible in tests.

Image that you had a typo, so your code was something like this:

```
setup do
    @image = Image.create!(ur: 'https://url.jpg')
  end

  def test_show
    get image_path(@image.id)

    assert_response :ok
    assert_select 'img.img[src=?]', @image.url
end
```

Let's assume there are no validations on `url` presence, so `@image` would be successfully created, but `@image.url` would actually be `nil`. So now line 12 will pass, but we don't actually have a value for `src`!

You may think that it is far-fetched that you could have a typo in the attribute name and that there would be no validations. However, you'll find that most apps use special test objects called "exemplars" that give us nice defaults for things, so it's easier have typo or misassignment of an attribute without it being detected.

TL;DR, I would change this line to 
```
assert_select 'img.img[src=?]', 'https://url.jpg'
```

2021-07-09 00:19 UTC, sarahsehr commented on test/controllers/images_controller_test.rb
> +    assert_equal('https://some-url.png', Image.last.url)
Do you see any performance implications with calling `Image.last` twice?

2021-07-09 00:19 UTC, sarahsehr commented on test/controllers/images_controller_test.rb
> +    assert_response :unprocessable_entity
How do we know that `new` is being rendered?

2021-07-12 15:07 UTC, kimiamajd98 commented on test/controllers/images_controller_test.rb
> +    assert_equal('https://some-url.png', Image.last.url)
It's probably better to save Image.last in a local variable so that I don't need to call last twice

2021-07-12 15:12 UTC, kimiamajd98 commented on test/controllers/images_controller_test.rb
> +    assert_response :unprocessable_entity
I added assertions to check that the form is being rendered

2021-07-12 15:28 UTC, kimiamajd98 commented on test/models/image_test.rb
> +  def test_image__valid
I added tests to cover the other image extensions. It seems to me that all the code in the images file has a test where if the code was deleted, a test would fail.

2021-07-12 16:25 UTC, sarahsehr approved these changes
Nice work! This looks quite clean. :)

Let's not worry about it for this story, but one of the things that would be good for the next story is to make commits that will be more helpful as a history (putting related things together). This would be a great topic to discuss with Joe.

2021-07-12 16:54 UTC, merged